### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by rpowis** [hmrc/design-patterns#33] opened 2017-01-31 13:30 UTC
# Screenshots

![image](https://cloud.githubusercontent.com/assets/1752124/22466713/d014aea8-e7c1-11e6-9744-9394965a5113.png)

![image](https://cloud.githubusercontent.com/assets/1752124/22466721/e088d836-e7c1-11e6-81d3-49227c839a5f.png)

**Comment by gavinwye** [comment] 2017-10-02 08:54
Duplicate of #81

**Closed by gavinwye** 2017-10-02 08:54 UTC
