### ISSUE TITLE
Start

### ISSUE THREAD

**Issue by feedmypixel** [hmrc/design-patterns#32] opened 2017-01-31 13:29 UTC
# Description
Start Pages

# Screenshot
![pla - welcome](https://cloud.githubusercontent.com/assets/2305016/22466677/46ba96ca-e7b9-11e6-8b26-f80beebcb4d3.png)

# Service Manual
https://www.gov.uk/service-manual/design/start-pages

**Comment by gavinwye** [comment] 2017-08-31 13:56
closing this as it's a duplicate of #21

**Closed by gavinwye** 2017-08-31 13:56 UTC
