### ISSUE TITLE
Technical difficulties

### ISSUE THREAD

**Issue by rpowis** [hmrc/design-patterns#59] opened 2017-01-31 14:06 UTC
# Existing Examples

![image](https://cloud.githubusercontent.com/assets/1752124/22467858/9157ad3c-e7c6-11e6-974b-c4cbb0600711.png)

---

![image](https://cloud.githubusercontent.com/assets/1752124/22467873/a4129dec-e7c6-11e6-92b5-342765e4cd7e.png)

---

![image](https://cloud.githubusercontent.com/assets/1752124/22467882/aa6b9b58-e7c6-11e6-8fd4-dbcce8dba989.png)

---

![image](https://cloud.githubusercontent.com/assets/1752124/22467890/b2dece68-e7c6-11e6-9d9f-e922f392c2ab.png)

---

![image](https://cloud.githubusercontent.com/assets/1752124/22467909/be4ecf46-e7c6-11e6-9bf9-91643a4f5890.png)

# GOV.UK Patterns

http://hmrc-shutter-pages.herokuapp.com/suggestions/

**Comment by stevenaproctor** [comment] 2017-10-17 09:28
@gavinwye Similar to #29.

**Comment by gavinwye** [comment] 2017-10-20 10:41
closing as a duplicate of #29 and #105

**Closed by gavinwye** 2017-10-20 10:41 UTC
